name: ClipPaste
options:
  bundleIdPrefix: com.clippaste
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: ClipPaste
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "2"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: ""

targets:
  ClipPaste:
    type: application
    platform: macOS
    sources:
      - path: ClipPaste
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: ClipPaste/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.clippaste.app
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: ClipPaste/ClipPaste.entitlements
